name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build and publish release
    runs-on: ubuntu-latest

    steps:
      - name: Clone cc-lucrative-deal
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt update; sudo apt install zip
        
      - name: Create CCLD archives
        run: |
          zip -q -r cc-lucrative-deal.ccmod ./*
          tar -czf cc-lucrative-deal.tar.gz --transform 's,^,cc-lucrative-deal/,' ./*
          
      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
        
      - name: Create release
        run: |
          gh release create ${{ steps.get_version.outputs.VERSION }} -t "Lucrative Deal ${{ steps.get_version.outputs.VERSION }}" ${{ env.FILES }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILES: cc-lucrative-deal.ccmod cc-lucrative-deal.tar.gz
